#!/bin/bash

# put this into PATH and then add to your .gitconfig
# [alias]
#     sgrep = "!f() { git-submodule-grep $@; }; f"


for m in `git submodule foreach --recursive | awk -F"'" '{ print $2;}'`
do
    if [[ $m =~ ^$GIT_PREFIX ]]
    then
        mod="$mod $m"
    else
        # submodule $m is not in path - skipping
        continue
    fi
done

export DIR=$GIT_PREFIX

(
git --no-pager grep $@ -- $DIR
if [ $? == 128 ]
then
    exit 1
fi
for m in $mod
do
    (cd $m
    git --no-pager grep $@ |
        while read match
            do echo $m/$match
        done)
done
) | sed s+^$GIT_PREFIX++ | pager
